backend:
  name: github
  branch: master
  repo: marvin-hinkley/hugo-quickstart
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "article"
    label: "Article"
    folder: "content/article"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
  - name: "pages"
    label: "Pages"
    files:
      - name: "index"
        label: "Index Page"
        file: "content/index.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - {
              label: "Date",
              name: "description",
              widget: "date",
              format: "YYYY-MM-DD",
            }
          - { label: "Slug", name: "slug", widget: "string" }
          - { label: "Content", name: "content", widget: "markdown" }
          - { label: "Layout", name: "layout", widget: "string" }
